//! Generated schema builders for FuguDB indexes
//! This file contains the schema builders that would normally be generated by build.rs

use tantivy::schema::*;

/// Build the docs schema - contains full document records with all fields
pub fn build_docs_schema(mut schema_builder: SchemaBuilder) -> Schema {
    // Core fields
    schema_builder.add_text_field("id", TEXT | STORED);
    schema_builder.add_text_field("text", TEXT | STORED);
    schema_builder.add_text_field("namespace", TEXT | STORED);

    // Optional fields from ObjectRecord
    schema_builder.add_text_field("name", TEXT | STORED);
    schema_builder.add_text_field("organization", TEXT | STORED);
    schema_builder.add_text_field("conversation_id", TEXT | STORED);
    schema_builder.add_text_field("data_type", TEXT | STORED);

    // Facet field for hierarchical filtering
    schema_builder.add_facet_field("facet", INDEXED | STORED);

    // Metadata as JSON object
    schema_builder.add_json_field("metadata", STORED);

    // Date fields
    schema_builder.add_date_field("date_created", INDEXED | STORED);
    schema_builder.add_date_field("date_updated", INDEXED | STORED);
    schema_builder.add_date_field("date_published", INDEXED | STORED);

    schema_builder.build()
}

/// Build the filter index schema - optimized for facet filtering
pub fn build_filter_index_schema(mut schema_builder: SchemaBuilder) -> Schema {
    // Core text field for search
    schema_builder.add_text_field("text", TEXT | STORED);
    
    // Facet field as text for searchable facet paths
    schema_builder.add_text_field("facet", TEXT | STORED);
    
    // Facet field for hierarchical filtering (mirrors the text field)
    schema_builder.add_facet_field("facet_hierarchy", INDEXED | STORED);
    
    // Namespace for multi-tenant filtering
    schema_builder.add_text_field("namespace", TEXT | STORED);

    schema_builder.build()
}

/// Build the query index schema - optimized for query suggestions
pub fn build_query_index_schema(mut schema_builder: SchemaBuilder) -> Schema {
    // Core text field for query suggestions
    schema_builder.add_text_field("text", TEXT | STORED);
    
    // Optional namespace for scoped suggestions
    schema_builder.add_text_field("namespace", TEXT | STORED);

    schema_builder.build()
}